import { CATEGORIES as CATEGORY_LIST, CATEGORY_RU } from './categories.js';

const RESOURCE_KEYS = Object.freeze(['gold', 'wood', 'metal', 'marble', 'glass', 'powder']);

const PRESETS = Object.freeze({
  cost: {
    LOW: { gold: 40, wood: 25, glass: 5, powder: 0, marble: 0, metal: 5 },
    MED: { gold: 120, wood: 50, glass: 15, powder: 0, marble: 5, metal: 15 },
    HIGH: { gold: 260, wood: 80, glass: 25, powder: 5, marble: 15, metal: 30 },
    VERY_HIGH: { gold: 520, wood: 120, glass: 45, powder: 15, marble: 35, metal: 60 },
  },
  upkeepPerMin: {
    LOW: { gold: 1, wood: 0, glass: 0, powder: 0, marble: 0, metal: 0 },
    MED: { gold: 3, wood: 0, glass: 0, powder: 0, marble: 0, metal: 0 },
    HIGH: { gold: 7, wood: 0, glass: 0, powder: 0, marble: 0, metal: 0 },
    VERY_HIGH: { gold: 15, wood: 0, glass: 0, powder: 0, marble: 0, metal: 0 },
  },
  buildTimeSec: {
    FAST: 10,
    NORMAL: 20,
    SLOW: 40,
    VERY_SLOW: 60,
  },
});

export const BUILDING_SYSTEM = Object.freeze({
  uiPlacementColors: {
    validAndAffordable: '#35C759',
    invalid: '#FF3B30',
    validButUnaffordable: '#FFCC00',
  },
  zonePolicy: {
    zoneVisualization: 'TILE_FILL',
    requireAllFootprintTilesInZone: true,
    conflictResolution: {
      mode: 'NEAREST_ZONE_SOURCE',
      tieBreakers: ['HIGHER_ZONE_PRIORITY', 'LOWER_CITY_ID'],
    },
  },
});

const zeroCosts = () => ({ gold: 0, wood: 0, metal: 0, marble: 0, glass: 0, powder: 0 });

const fillResources = (input) => ({ ...zeroCosts(), ...(input ?? {}) });

const normalize = (raw) => {
  const cost = raw.economy?.costOverride ?? PRESETS.cost[raw.economy?.costPreset] ?? zeroCosts();
  const upkeep = raw.economy?.upkeepOverride ?? PRESETS.upkeepPerMin[raw.economy?.upkeepPreset] ?? { gold: 0 };
  const addsBuildZone = raw.zoneContribution?.addsBuildZone ?? false;
  const baseZoneRadiusTiles = 10;
  const configuredZoneRadius = Number(raw.zoneContribution?.radius ?? 0);
  const zoneRadiusTiles = addsBuildZone
    ? (configuredZoneRadius > 0 ? configuredZoneRadius : baseZoneRadiusTiles)
    : 0;

  return {
    id: raw.id,
    name: raw.ui?.nameRu ?? raw.id,
    category: CATEGORY_RU[raw.category] ?? raw.category,
    tier: raw.tier ?? 1,
    uniquePerCity: Boolean(raw.unique?.perCity),
    uniquePerPlayer: Boolean(raw.unique?.perPlayer),
    size: raw.size ?? { w: 1, h: 1 },
    footprint: raw.footprint ?? ['1'],
    buildCost: fillResources(cost),
    buildTimeSec: PRESETS.buildTimeSec[raw.economy?.buildTimePreset] ?? 20,
    upkeepPerMin: fillResources(upkeep),
    isHub: Boolean(raw.isHub),
    isStarter: Boolean(raw.isStarter),
    placementRules: {
      allowedSurfaces: raw.placementRules?.allowedSurfaces ?? null,
      forbiddenSurfaces: raw.placementRules?.forbiddenSurfaces ?? null,
      mustBeInsideBuildZone: raw.placementRules?.mustBeInsideBuildZone ?? true,
      canBeOutsideBuildZone: raw.placementRules?.canBeOutsideBuildZone ?? false,
      maxDistanceToBuildZone: raw.placementRules?.maxDistanceToBuildZone ?? 0,
      requiresResourceNode: raw.placementRules?.requiresResourceNode
        ? { type: String(raw.placementRules.requiresResourceNode.type).toLowerCase(), radiusTiles: raw.placementRules.requiresResourceNode.radius }
        : null,
      requiresCoast: raw.placementRules?.requiresCoast ?? false,
      limit: {
        perCity: raw.unique?.perCity ? raw.unique.perCity : null,
        perPlayer: raw.unique?.perPlayer ? raw.unique.perPlayer : null,
      },
    },
    buildZone: {
      addsBuildZone,
      zoneShape: raw.zoneContribution?.shape === 'NONE' ? 'TILE_DISK' : (raw.zoneContribution?.shape ?? 'TILE_DISK'),
      zoneRadiusTiles,
      zonePriority: raw.zoneContribution?.priority ?? 0,
    },
    effects: raw.effects ?? [],
    ui: {
      descriptionShort: raw.ui?.shortRu ?? '',
      descriptionLong: raw.ui?.descriptionRu ?? '',
      tags: raw.ui?.tagsRu ?? [],
    },
  };
};

const RAW_BUILDINGS = [
  { id: 'GOV_TOWN_HALL', isHub: true, category: 'GOVERNANCE', tier: 1, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: false, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: true, shape: 'TILE_DISK', radius: 20, priority: 100 }, effects: [{ type: 'TaxEfficiency', mode: 'ADD', value: 0.05, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'BuildQueueSlots', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Городская управа (Ратуша)', shortRu: 'Якорь города: управление, сметы, разрешения.', descriptionRu: 'Главный дом городского правления: здесь ведутся книги сборов и выдаются разрешения.', tagsRu: ['присутственное место', 'основа'] } },
  { id: 'GOV_CHANCELLERY', category: 'GOVERNANCE', tier: 1, size: { w: 1, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'BuildSpeed', mode: 'MUL', value: 1.1, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'Corruption', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Канцелярия', shortRu: 'Дела идут быстрее — но приписки растут.', descriptionRu: 'Контора писарей и делопроизводителей ускоряет документы и сметы.', tagsRu: ['делопроизводство', 'ускорение'] } },
  { id: 'GOV_COURTHOUSE', category: 'GOVERNANCE', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'Crime', mode: 'ADD', value: -2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Corruption', mode: 'ADD', value: -2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Окружной суд', shortRu: 'Давит злоупотребления — стоит дорого.', descriptionRu: 'Присутственное место, где тяжбы и злоупотребления решаются печатью закона.', tagsRu: ['правосудие', 'порядок'] } },
  { id: 'GOV_CENSUS_BUREAU', category: 'GOVERNANCE', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TaxEfficiency', mode: 'MUL', value: 1.2, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'Happiness', mode: 'ADD', value: -2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'EventRisk_Revolt', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Corruption', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Статистическое бюро (Перепись)', shortRu: 'Казна видит всё — народ ворчит.', descriptionRu: 'Учёт дворов и промыслов помогает налогам, но вызывает недовольство.', tagsRu: ['учёт', 'жёсткая рука', 'риск волнений'] } },
  { id: 'GOV_PRESS_BUREAU', category: 'GOVERNANCE', tier: 2, size: { w: 1, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'Happiness', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'WarTension', mode: 'ADD', value: -1, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Corruption', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Пресс-бюро', shortRu: 'Слова лечат тревогу, но шумят.', descriptionRu: 'Газета и объявления снижают тревогу, но плодят шум и кривду.', tagsRu: ['газета', 'объявления'] } },

  { id: 'HOU_HUTS', category: 'HOUSING', tier: 1, size: { w: 1, h: 1 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'LOW', buildTimePreset: 'FAST' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'forest'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'PopCap', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Слободские хижины', shortRu: 'Дёшево и быстро, но без удобств.', descriptionRu: 'Простые дворы для работного люда.', tagsRu: ['простое жильё'] } },
  { id: 'HOU_HOUSES', category: 'HOUSING', tier: 1, size: { w: 1, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'LOW', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'PopCap', mode: 'ADD', value: 4, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Мещанские дома', shortRu: 'Добротное жильё для стабильного квартала.', descriptionRu: 'Добротные дома делают квартал чиннее.', tagsRu: ['жильё', 'квартал'] } },
  { id: 'HOU_TENEMENTS', category: 'HOUSING', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'PopCap', mode: 'ADD', value: 10, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Crime', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Доходные дома', shortRu: 'Много жильцов — много хлопот.', descriptionRu: 'Плотная застройка повышает вместимость ценой порядка.', tagsRu: ['плотность', 'риск'] } },
  { id: 'HOU_ESTATES', category: 'HOUSING', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'Happiness', mode: 'ADD', value: 3, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'TaxEfficiency', mode: 'ADD', value: 0.03, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'PopCap', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Особняки', shortRu: 'Благополучие квартала — за большую цену.', descriptionRu: 'Состоятельная застройка укрепляет налоговую базу.', tagsRu: ['элита', 'стабильность'] } },
  { id: 'HOU_MEGABLOCK', category: 'HOUSING', tier: 3, size: { w: 3, h: 3 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'PopCap', mode: 'ADD', value: 30, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'GrowthRate', mode: 'MUL', value: 1.15, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'Crime', mode: 'ADD', value: 4, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -4, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Жилой корпус-гигант', shortRu: 'Люди и рост — ценой тесноты и смуты.', descriptionRu: 'Исполинский жилой корпус на тысячи жильцов.', tagsRu: ['оверпауэр', 'социальное напряжение'] } },

  { id: 'EXP_EXPANSION_POST', category: 'EXPANSION', tier: 1, size: { w: 1, h: 1 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, allowedSurfaces: ['land', 'forest', 'hill', 'mountain', 'coast', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: true, shape: 'TILE_DISK', radius: 12, priority: 60 }, effects: [{ type: 'Overextension', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Окраинный пост', shortRu: 'Тянет застройку дальше.', descriptionRu: 'Пост с караулкой размечает новые границы.', tagsRu: ['экспансия', 'зона'] } },
  { id: 'EXP_ROAD_JUNCTION', category: 'EXPANSION', tier: 1, size: { w: 1, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'LOW', buildTimePreset: 'FAST' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['road', 'land'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TradeSpeed', mode: 'MUL', value: 1.05, scope: 'City', radius: 0, stacking: 'MUL' }], ui: { nameRu: 'Трактовый узел', shortRu: 'Обозы идут бодрее.', descriptionRu: 'Перекрёсток с шлагбаумом сокращает задержки.', tagsRu: ['дороги', 'логистика'] } },
  { id: 'EXP_SURVEY_BEACON', category: 'EXPANSION', tier: 1, size: { w: 1, h: 1 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'LOW', buildTimePreset: 'FAST' }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, allowedSurfaces: ['land', 'hill', 'mountain', 'coast'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'SpecialBuildMaxDistanceBonus', mode: 'ADD', value: 5, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Геодезический знак', shortRu: 'Промеры и разведка местности быстрее.', descriptionRu: 'Ориентир помогает промерам под новые промыслы.', tagsRu: ['разведка', 'промеры'] } },
  { id: 'EXP_FORWARD_OUTPOST', category: 'EXPANSION', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW', costOverride: { powder: 10, gold: 260, wood: 80, glass: 25, marble: 15, metal: 30 } }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, allowedSurfaces: ['land', 'hill', 'coast', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: true, shape: 'TILE_DISK', radius: 10, priority: 80 }, effects: [{ type: 'Defense', mode: 'ADD', value: 3, scope: 'Radius', radius: 8, stacking: 'ADD' }, { type: 'WarTension', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Передовой редут', shortRu: 'Опорный пункт и зона — ценой напряжения.', descriptionRu: 'Укреплённый пункт на окраине для обороны рубежа.', tagsRu: ['укрепление', 'граница'] } },
  { id: 'EXP_EXPEDITION_HQ', category: 'EXPANSION', tier: 3, size: { w: 3, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'SpecialBuildMaxDistanceBonus', mode: 'ADD', value: 50, scope: 'Global', radius: 0, stacking: 'ADD' }, { type: 'Corruption', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Штаб экспедиции', shortRu: 'Дальние работы становятся возможны.', descriptionRu: 'Контора экспедиционных работ для освоения дальних участков.', tagsRu: ['оверпауэр', 'освоение окраин'] } },

  { id: 'TRD_MARKET', category: 'TRADE', tier: 1, size: { w: 2, h: 1 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'LOW', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TradeCapacity', mode: 'ADD', value: 5, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'IncomeGold', mode: 'ADD', value: 6, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Crime', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Гостиный двор (Рынок)', shortRu: 'Доход и оборот — вместе с шулерами.', descriptionRu: 'Торговые ряды увеличивают оборот и доход города.', tagsRu: ['торг', 'монета'] } },
  { id: 'TRD_WAREHOUSE', category: 'TRADE', tier: 1, size: { w: 2, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TradeSpeed', mode: 'MUL', value: 1.03, scope: 'City', radius: 0, stacking: 'MUL' }], ui: { nameRu: 'Пакгауз (Склад)', shortRu: 'Меньше потерь и задержек.', descriptionRu: 'Складские корпуса повышают надёжность перевозок.', tagsRu: ['склад', 'учёт'] } },
  { id: 'TRD_CARAVANSERAI', category: 'TRADE', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TradeCapacity', mode: 'MUL', value: 1.15, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'TradeSpeed', mode: 'MUL', value: 1.1, scope: 'City', radius: 0, stacking: 'MUL' }], ui: { nameRu: 'Торговый двор', shortRu: 'Оживляет караваны.', descriptionRu: 'Двор для обозов: стоянка, ремонт и ночлег.', tagsRu: ['караваны', 'обоз'] } },
  { id: 'TRD_PORT', category: 'TRADE', tier: 2, size: { w: 3, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['coast'], forbiddenSurfaces: ['water'], requiresCoast: true }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TradeCapacity', mode: 'MUL', value: 1.2, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'IncomeGold', mode: 'ADD', value: 10, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Smuggling', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Портовая контора и причалы', shortRu: 'Ворота для товаров.', descriptionRu: 'Причалы и таможенный стол открывают морскую торговлю.', tagsRu: ['порт', 'таможня'] } },
  { id: 'TRD_FREE_HARBOR', category: 'TRADE', tier: 3, size: { w: 3, h: 3 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['coast'], forbiddenSurfaces: ['water'], requiresCoast: true }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'IncomeGold', mode: 'MUL', value: 1.35, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'TradeCapacity', mode: 'MUL', value: 1.35, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'Smuggling', mode: 'ADD', value: 3, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Crime', mode: 'ADD', value: 3, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Corruption', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Вольная гавань', shortRu: 'Огромный оборот — огромная тень.', descriptionRu: 'Режим вольной торговли кратно увеличивает оборот.', tagsRu: ['оверпауэр', 'контрабанда'] } },

  { id: 'FIN_TREASURY', category: 'FINANCE', tier: 1, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'IncomeStability', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'TaxEfficiency', mode: 'ADD', value: 0.02, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Казначейство', shortRu: 'Доходы ровнее.', descriptionRu: 'Казённая палата стабилизирует доходы и отчётность.', tagsRu: ['казна', 'ведомости'] } },
  { id: 'FIN_TAX_OFFICE', category: 'FINANCE', tier: 1, size: { w: 1, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'LOW', buildTimePreset: 'FAST' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'TaxEfficiency', mode: 'ADD', value: 0.04, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -1, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'EventRisk_Revolt', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Податная контора', shortRu: 'Казна полнее — народ ворчит.', descriptionRu: 'Сборщики податей усиливают наполнение казны.', tagsRu: ['подати', 'сбор'] } },
  { id: 'FIN_MINT', category: 'FINANCE', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'IncomeGold', mode: 'ADD', value: 8, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'TradeCapacity', mode: 'ADD', value: 3, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Монетный двор', shortRu: 'Деньги становятся крепче.', descriptionRu: 'Чеканка монеты делает торговлю увереннее.', tagsRu: ['чеканка', 'монета'] } },
  { id: 'FIN_BANK', category: 'FINANCE', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'CreditLimit', mode: 'ADD', value: 10, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'BuildSpeed', mode: 'MUL', value: 1.05, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'CrisisRisk', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Коммерческий банк', shortRu: 'Ссуды ускоряют стройку.', descriptionRu: 'Ссуды и векселя ускоряют проекты ценой риска паники.', tagsRu: ['кредит', 'векселя'] } },
  { id: 'FIN_CENTRAL_BANK', category: 'FINANCE', tier: 3, size: { w: 3, h: 2 }, unique: { perCity: 0, perPlayer: 1 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'InflationControl', mode: 'MUL', value: 1.25, scope: 'Global', radius: 0, stacking: 'MUL' }, { type: 'IncomeStability', mode: 'ADD', value: 4, scope: 'Global', radius: 0, stacking: 'ADD' }, { type: 'CreditLimit', mode: 'MUL', value: 1.25, scope: 'Global', radius: 0, stacking: 'MUL' }, { type: 'Happiness', mode: 'ADD', value: -2, scope: 'Global', radius: 0, stacking: 'ADD' }, { type: 'TradeSpeed', mode: 'MUL', value: 0.92, scope: 'Global', radius: 0, stacking: 'MUL' }, { type: 'EventRisk_Revolt', mode: 'ADD', value: 2, scope: 'Global', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Государственный банк', shortRu: 'Держит систему — но меры суровы.', descriptionRu: 'Главный банк стабилизирует систему суровой ценой.', tagsRu: ['оверпауэр', 'ставка'] } },

  { id: 'MIL_BARRACKS', category: 'MILITARY', tier: 1, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'RecruitCapacity', mode: 'ADD', value: 5, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Казармы', shortRu: 'Гарнизон и караулы.', descriptionRu: 'Размещение гарнизона усиливает порядок и призыв.', tagsRu: ['гарнизон', 'служба'] } },
  { id: 'MIL_TRAINING_GROUNDS', category: 'MILITARY', tier: 1, size: { w: 2, h: 1 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'MED', buildTimePreset: 'FAST' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'RecruitSpeed', mode: 'MUL', value: 1.15, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'UnitQuality', mode: 'ADD', value: 1, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Учебный плац', shortRu: 'Муштра быстрее.', descriptionRu: 'Плац и инструкторы ускоряют подготовку рекрутов.', tagsRu: ['муштра', 'подготовка'] } },
  { id: 'MIL_RANGE_SCHOOL', category: 'MILITARY', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'UnitQuality', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Стрелковая школа', shortRu: 'Прицельная наука и дисциплина.', descriptionRu: 'Тир и классы повышают качество подразделений.', tagsRu: ['стрельба', 'школа'] } },
  { id: 'MIL_ARSENAL', category: 'MILITARY', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW', costOverride: { powder: 10, gold: 260, wood: 80, glass: 25, marble: 15, metal: 30 }, upkeepOverride: { gold: 7, wood: 0, glass: 0, powder: 1, marble: 0, metal: 0 } }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'UpgradeCost', mode: 'MUL', value: 0.9, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'EventRisk_Fire', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Арсенал', shortRu: 'Снаряжение дешевле — риск пожаров выше.', descriptionRu: 'Оружейные склады удешевляют снабжение армии.', tagsRu: ['интендантство', 'риск пожара'] } },
  { id: 'MIL_WAR_OFFICE', category: 'MILITARY', tier: 3, size: { w: 3, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW', costOverride: { powder: 20, gold: 520, wood: 120, glass: 45, marble: 35, metal: 60 }, upkeepOverride: { gold: 15, wood: 0, glass: 0, powder: 1, marble: 0, metal: 0 } }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'RecruitCapacity', mode: 'MUL', value: 1.35, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'Defense', mode: 'ADD', value: 4, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -3, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'TradeCapacity', mode: 'MUL', value: 0.85, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'WarTension', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Военное ведомство', shortRu: 'Город-крепость.', descriptionRu: 'Канцелярия мобилизации превращает город в крепость.', tagsRu: ['оверпауэр', 'мобилизация'] } },

  { id: 'IND_SAWMILL', category: 'INDUSTRY', tier: 1, size: { w: 2, h: 1 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'LOW', upkeepPreset: 'LOW', buildTimePreset: 'NORMAL' }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, maxDistanceToBuildZone: 100, allowedSurfaces: ['forest'], forbiddenSurfaces: ['water'], requiresResourceNode: { type: 'TIMBER', radius: 2 } }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'ResourceYield', resource: 'wood', mode: 'ADD', value: 8, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -1, scope: 'Radius', radius: 6, stacking: 'ADD' }], ui: { nameRu: 'Лесопильня', shortRu: 'Доска идёт быстро — лес редеет.', descriptionRu: 'Пилорама даёт древесину для строек.', tagsRu: ['промысел', 'лес'] } },
  { id: 'IND_QUARRY', category: 'INDUSTRY', tier: 1, size: { w: 2, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'MED', upkeepPreset: 'MED', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, maxDistanceToBuildZone: 100, allowedSurfaces: ['hill', 'mountain'], forbiddenSurfaces: ['water'], requiresResourceNode: { type: 'MARBLE', radius: 2 } }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'ResourceYield', resource: 'marble', mode: 'ADD', value: 6, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Pollution', mode: 'ADD', value: 2, scope: 'Radius', radius: 6, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -1, scope: 'Radius', radius: 6, stacking: 'ADD' }], ui: { nameRu: 'Каменоломня (Мраморный карьер)', shortRu: 'Мрамор для солидных строек.', descriptionRu: 'Карьер даёт мрамор ценой пыли и шума.', tagsRu: ['карьер', 'мрамор'] } },
  { id: 'IND_MINE', category: 'INDUSTRY', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 0, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW', costOverride: { powder: 10, gold: 260, wood: 80, glass: 25, marble: 15, metal: 30 }, upkeepOverride: { gold: 7, wood: 0, glass: 0, powder: 1, marble: 0, metal: 0 } }, placementRules: { mustBeInsideBuildZone: false, canBeOutsideBuildZone: true, maxDistanceToBuildZone: 100, allowedSurfaces: ['mountain', 'hill'], forbiddenSurfaces: ['water'], requiresResourceNode: { type: 'ORE', radius: 2 } }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'ResourceYield', resource: 'metal', mode: 'ADD', value: 7, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'EventRisk_Accident', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Рудник', shortRu: 'Металл — кровь индустрии.', descriptionRu: 'Шахты дают металл ценой высокой аварийности.', tagsRu: ['шахта', 'порох'] } },
  { id: 'IND_SMELTER', category: 'INDUSTRY', tier: 2, size: { w: 2, h: 2 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'HIGH', upkeepPreset: 'HIGH', buildTimePreset: 'SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'ResourceYield', resource: 'metal', mode: 'ADD', value: 3, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Pollution', mode: 'ADD', value: 3, scope: 'Radius', radius: 8, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -1, scope: 'Radius', radius: 8, stacking: 'ADD' }], ui: { nameRu: 'Плавильня', shortRu: 'Металл и детали — дым и расходы.', descriptionRu: 'Печи и литейные формы поднимают переработку металла.', tagsRu: ['печи', 'литейная'] } },
  { id: 'IND_INDUSTRIAL_COMPLEX', category: 'INDUSTRY', tier: 3, size: { w: 3, h: 3 }, unique: { perCity: 1, perPlayer: 0 }, economy: { costPreset: 'VERY_HIGH', upkeepPreset: 'VERY_HIGH', buildTimePreset: 'VERY_SLOW' }, placementRules: { mustBeInsideBuildZone: true, allowedSurfaces: ['land', 'road'], forbiddenSurfaces: ['water'] }, zoneContribution: { addsBuildZone: false, shape: 'NONE', radius: 0, priority: 0 }, effects: [{ type: 'ProductionAll', mode: 'MUL', value: 1.25, scope: 'City', radius: 0, stacking: 'MUL' }, { type: 'ResourceYield', resource: 'metal', mode: 'ADD', value: 4, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Pollution', mode: 'ADD', value: 5, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Crime', mode: 'ADD', value: 2, scope: 'City', radius: 0, stacking: 'ADD' }, { type: 'Happiness', mode: 'ADD', value: -3, scope: 'City', radius: 0, stacking: 'ADD' }], ui: { nameRu: 'Промышленный комбинат', shortRu: 'Выпуск огромный — город темнеет от копоти.', descriptionRu: 'Комбинат полного цикла резко усиливает производство.', tagsRu: ['оверпауэр', 'комбинат'] } },
];

export const CATEGORIES = CATEGORY_LIST;
export const BUILDINGS = Object.freeze(RAW_BUILDINGS.map(normalize));

const BUILDINGS_BY_ID = new Map(BUILDINGS.map((building) => [building.id, building]));

export function getBuildingDef(id) {
  return BUILDINGS_BY_ID.get(id) ?? null;
}

export function listBuildingsByCategory(category) {
  return BUILDINGS.filter((building) => building.category === category);
}

export const BUILDING_CATALOG_RESOURCES = RESOURCE_KEYS;
