export const CATEGORY_KEYS = Object.freeze({
  GOVERNANCE: 'GOVERNANCE',
  HOUSING: 'HOUSING',
  EXPANSION: 'EXPANSION',
  TRADE: 'TRADE',
  FINANCE: 'FINANCE',
  MILITARY: 'MILITARY',
  INDUSTRY: 'INDUSTRY',
});

export const CATEGORY_RU = Object.freeze({
  [CATEGORY_KEYS.GOVERNANCE]: 'Управление',
  [CATEGORY_KEYS.HOUSING]: 'Жильё',
  [CATEGORY_KEYS.EXPANSION]: 'Экспансия',
  [CATEGORY_KEYS.TRADE]: 'Торговля',
  [CATEGORY_KEYS.FINANCE]: 'Финансы',
  [CATEGORY_KEYS.MILITARY]: 'Армия',
  [CATEGORY_KEYS.INDUSTRY]: 'Добыча',
});

export const CATEGORIES = Object.freeze([
  CATEGORY_RU[CATEGORY_KEYS.GOVERNANCE],
  CATEGORY_RU[CATEGORY_KEYS.HOUSING],
  CATEGORY_RU[CATEGORY_KEYS.EXPANSION],
  CATEGORY_RU[CATEGORY_KEYS.TRADE],
  CATEGORY_RU[CATEGORY_KEYS.FINANCE],
  CATEGORY_RU[CATEGORY_KEYS.MILITARY],
  CATEGORY_RU[CATEGORY_KEYS.INDUSTRY],
]);
