export const EFFECT_TYPES = Object.freeze({
  TaxEfficiency: 'TaxEfficiency',
  IncomeGold: 'IncomeGold',
  BuildSpeed: 'BuildSpeed',
  BuildQueueSlots: 'BuildQueueSlots',
  Corruption: 'Corruption',
  Crime: 'Crime',
  Happiness: 'Happiness',
  PopCap: 'PopCap',
  GrowthRate: 'GrowthRate',
  TradeCapacity: 'TradeCapacity',
  TradeSpeed: 'TradeSpeed',
  IncomeStability: 'IncomeStability',
  CreditLimit: 'CreditLimit',
  CrisisRisk: 'CrisisRisk',
  InflationControl: 'InflationControl',
  RecruitCapacity: 'RecruitCapacity',
  RecruitSpeed: 'RecruitSpeed',
  UnitQuality: 'UnitQuality',
  UpgradeCost: 'UpgradeCost',
  Defense: 'Defense',
  Overextension: 'Overextension',
  WarTension: 'WarTension',
  Smuggling: 'Smuggling',
  Pollution: 'Pollution',
  EventRisk_Revolt: 'EventRisk_Revolt',
  EventRisk_Fire: 'EventRisk_Fire',
  EventRisk_Accident: 'EventRisk_Accident',
  SpecialBuildMaxDistanceBonus: 'SpecialBuildMaxDistanceBonus',
  ProductionAll: 'ProductionAll',
  ResourceYield: 'ResourceYield',
});

export const EFFECT_TYPE_LIST = Object.freeze(Object.values(EFFECT_TYPES));
